### ISSUE TITLE
脚本没有正常输出

### ISSUE THREAD

**Issue by laiyuanbiu** [Oniicyan/BTNScriptBC#1]
脚本启动后输出更新就停留在
2024/8/26 19:45:05 [ BTNScriptBC 开始循环工作 ]
2024/8/26 19:45:05 [ 每 1500 秒提交 Peers 快照 ]
2024/8/26 19:45:05 [ 每 1500 秒查询 BTN 封禁规则更新 ]
2024/8/26 19:45:05 [ 每 3600 秒查询 IP 黑名单订阅更新 ]
2024/8/26 19:45:05 [ 每 10800 秒查询 BTN 服务器配置更新 ]

然后大半天都没有输出更新任何内容，比特彗星都已经有正在做种跟上传的用户（甚至是吸血客户端101.69.63.30:8216）
![15403f6d2b8f17d7e688dfd642ec7da26cd7294b](https://github.com/user-attachments/assets/756eefa9-e1c5-491b-a076-cde071fe6ce4)

**Comment by Oniicyan** [comment]
可能是运行了正在调试的脚本
我直接在 GitHub 上改代码后再下载到本地测试，因此有可能推送不可靠的版本（

脚本行为已变更，初次启动会先更新 IP 黑名单订阅，再执行 BTN 任务
现在可右键点击通知区域图标，强制执行提交和更新的操作
