### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by NeilTohno** [Oniicyan/BTNScriptBC#2]
大佬你好，这个怎么办

https://btn-prod.ghostchu-services.top/

显示 504 Gateway Timeout

用这个就没有什么问题哈
https://github.com/Oniicyan/BT_BAN

**Comment by Oniicyan** [comment]
BTN Sparkle 服务器还在开发改进阶段，偶尔会出现维护或访问困难的情况，通常换个时间再试就可以。
