### ISSUE TITLE
请问能否创建本地化更新脚本

### ISSUE THREAD

**Issue by NeilTohno** [Oniicyan/BTNScriptBC#3]
我理解云端脚本有一定优势，但是还是会经常连接不上的情况，
用户也不一定有时间处理这些问题，可能他发现用几次连不上就放弃使用了，
所以还是请求一个本地化的更新脚本，像 UsbEAm Hosts Editor 一样用就行啊

https://github.com/Oniicyan/BT_BAN
这个也一样

**Comment by Oniicyan** [comment]
BTNScriptBC 可以改为初始配置完成后在本地创建脚本执行，并定期检查更新
之前主要是因为改动比较频繁，没有考虑这方面

BT_BAN 的话，脚本和 IP 列表在同一服务器上，即使脚本保存在本地，IP 列表获取不到也无意义
目前 BT_BAN 是每小时更新，一分钟间隔重试 5 次失败就跳过且弹出失败通知
而 BT_BAN 设计上是允许更新失败的，并不影响当前的封禁效果（但会损失一点时效性）

**Comment by NeilTohno** [comment]
> BTNScriptBC 可以改为初始配置完成后在本地创建脚本执行，并定期检查更新 之前主要是因为改动比较频繁，没有考虑这方面
> 
> BT_BAN 的话，脚本和 IP 列表在同一服务器上，即使脚本保存在本地，IP 列表获取不到也无意义 目前 BT_BAN 是每小时更新，一分钟间隔重试 5 次失败就跳过且弹出失败通知 而 BT_BAN 设计上是允许更新失败的，并不影响当前的封禁效果（但会损失一点时效性）

感谢回复，
但是连接不上服务器，虽然本地有上次的同步的 IP 列表，没法利用 iex (irm btn-bc.pages.dev/add) 添加，除去规则啊。

**Comment by Oniicyan** [comment]
>没法利用 iex (irm btn-bc.pages.dev/add) 添加，除去规则

`add` 设计上是用于单次的配置，并没有考虑需要频繁添加、删除过滤规则的情况

Windows 防火墙中，过滤规则与动态关键字互相关联但不依赖，更新动态关键字无需对过滤规则进行改动

若确实有特殊的场景需要频繁 `add`，可以考虑把 `BTNScriptBC_ADDFW.ps1` 下载至本地执行
`add` 的执行过程并不需要联网

---

已修改为保存脚本到本地执行，下次启动脚本时自动生效
